name: Git Version gitflow

on:
  # 触发工作流程的事件
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # 允许手动触发工作流程
  workflow_dispatch:

jobs:
  look-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          useConfigFile: true
          configFilePath: VersionConfig.yml
